### ISSUE TITLE
Changing default language to ...

### ISSUE THREAD

**Issue by ywolynsky** [t-markmann/nc-userimporter#11]
Hi there,

thanks for your great script for creating new users.
It really saves me a lot of time.

Is there a possibility to change the language to e.g. german so that user get a email written in their preferred language. Is would be nice if this can be set for creating the pdf too.

By creating new users a group admin has to be defined. 
I dont want users to be able to add new users or add groups within their admin group.
How can i achieve this? 

Thanks for your advice :-)

**Comment by t-markmann** [comment]
Hi! Thanks for you feedback.

We will add a default language, yes. This is already on the ToDo list: https://github.com/t-markmann/nc-userimporter#todo
I just cannot give you time estimate.... maybe I have time for that in the next weeks.

Language for the PDF file: this is a lot more work because there are no translations for the final PDF sheets. Just english and german. I think you can switch on "EduDocs-Mode" to get a german output file.

Regarding group admins: you can just leave this field empty. It is like setting the group-admin field in the Nextcloud web interface. If you set this field, you give the new user groupadmin permissions for the specified group(s). 

Hope this helps!

**Comment by t-markmann** [comment]
Closed by https://github.com/t-markmann/nc-userimporter/commit/b7e0c088f298bab5b1cef2c553786980e16995b2
